image: Visual Studio 2017
version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Tokenizer\Tokenizer.Demo\bin\Release
  name: TokenizerDemo
