version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: cd Tokenizer && nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Tokenizer\Tokenizer.Demo\bin\Release
  name: Demo

